version: '3'

services:
  db:
    image: mariadb
    restart: always
    container_name: db
    volumes:
      - ./src/app/mysql/:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test

  api:
    image: webapp
    restart: always
    container_name: mywebapp
    depends_on:
      - db
    build:
        context: ./src
    ports:
      - "8009:8080"
    develop:
      watch:
        - action: rebuild
          path: ./src/app/src
        - action: rebuild
          path: ./src/app
          target: index.html

